build:
  no_build: true

clusters:
  test-cluster-props: &test-cluster-props
    spark_version: "12.2.x-cpu-ml-scala2.12"
    spark_env_vars:
      WRITE_ENV: "test"
      READ_ENV: "test"

  prod-cluster-props: &prod-cluster-props
    spark_version: "12.2.x-cpu-ml-scala2.12"
    spark_env_vars:
      WRITE_ENV: "prod"
      READ_ENV: "prod"

  test-cluster: &test-cluster
    new_cluster:
      <<: *test-cluster-props
      num_workers: 1
      instance_pool_id: "0712-081441-voile3-pool-dt4ut8z6"

  prod-cluster: &prod-cluster
    new_cluster:
      <<: *prod-cluster-props
      num_workers: 1
      instance_pool_id: "0712-081732-wham4-pool-j0p81582"

git:
  odap-git-source: &odap-git-source
    git_url: "https://github.com/DataSentics/odap.git"
    git_provider: "github"
    git_branch: "main"

environments:
  default:
    workflows:
      - name: "odap-prod-pipeline"
        git_source:
          <<: *odap-git-source
        job_clusters:
          - job_cluster_key: "default"
            <<: *prod-cluster
        tasks:
          - &init
            task_key: "init"
            job_cluster_key: "default"
            notebook_task:
              notebook_path: "odap_framework_demo/_demo/_setup/init"
          - &dry_run
            task_key: "dry_run"
            job_cluster_key: "default"
            notebook_task:
              notebook_path: "odap_framework_demo/orchestration/dry_run"
            depends_on:
              - task_key: "init"
          - &use-case-table
            task_key: "use-case-table"
            job_cluster_key: "default"
            notebook_task:
              notebook_path: "odap_framework_demo/orchestration/generate_use_case_table"
            depends_on:
              - task_key: "init"
          - &features
            task_key: "odap-features"
            job_cluster_key: "default"
            notebook_task:
              notebook_path: "odap_framework_demo/orchestration/features_orchestrator"
              base_parameters:
                target: "no target"
                timestamp: "2020-12-12"
            depends_on:
              - task_key: "init"
          - &uc-investment-export
            task_key: "upsell-uc-investment-interest-export"
            job_cluster_key: "default"
            notebook_task:
              notebook_path: "odap_framework_demo/orchestration/segments_orchestrator"
              base_parameters:
                export: "upsell_uc: upsell_uc_investment_interest"
            depends_on:
              - task_key: "odap-features"
          - &uc-loan-export
            task_key: "upsell-uc-loan-interest-export"
            job_cluster_key: "default"
            notebook_task:
              notebook_path: "odap_framework_demo/orchestration/segments_orchestrator"
              base_parameters:
                export: "upsell_uc: upsell_uc_loan_interest"
            depends_on:
              - task_key: "odap-features"

      - name: "odap-integration-test"
        git_source:
          <<: *odap-git-source
          git_branch: "{{env['GITHUB_HEAD_REF']}}"
        job_clusters:
          - job_cluster_key: "default"
            <<: *test-cluster
        tasks:
          - <<: *init
          - <<: *dry_run
          - <<: *use-case-table
          - <<: *features
          - <<: *uc-investment-export
          - <<: *uc-loan-export
