name: Deploy Production pipeline

on:
  push:
    branches:
      - 'main'

jobs:
  pipeline:
    runs-on: ubuntu-latest

    env:
      DATABRICKS_HOST: ${{ secrets.DATABRICKS_PROD_HOST }}
      DATABRICKS_TOKEN:  ${{ secrets.DATABRICKS_PROD_TOKEN }}

    defaults:
      run:
        working-directory: odap_framework_demo

    steps:
      - uses: actions/checkout@v1

      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          pip install -r requirements-dev.txt

      - name: Deploy production pipeline
        run: |
          dbx deploy prod-pipeline --deployment-file deployment.yaml
